export const FeatureType = Object.freeze({
  Motivo1: 1,
  Motivo2: 2,
  Motivo3: 3,
  TipoDeEntregableCierreDePlaza: 4,
  MatrizSODEntrada: 5,
  Selectivo: 6,
  Concurso: 7,
  Global: 10,
  Local: 12,
  Asimov: 13,
  ConcursoInterno1: 14,
  ConcursoExterno: 15,
  ConcursoInterno2: 16,
  Merito: 17,
  ConcursoInterno3: 18,
  DecisionInterna: 19,
  TForm: 21,
  CrecimientoDelNegocio: 22,
  TransformacionDesdeReSources: 23,
  Reestructuracion: 24,
  Maternidad: 25,
  Enfermedad: 26,
  NecesidadDeNegocio: 27,
});

export const FeatureTypeName = {
  [FeatureType.Motivo1]: "Motivo 1",
  [FeatureType.Motivo2]: "Motivo 2",
  [FeatureType.Motivo3]: "Motivo 3",
  [FeatureType.TipoDeEntregableCierreDePlaza]:
    "Tipo de entregable - Cierre de plaza",
  [FeatureType.MatrizSODEntrada]: "Matriz SOD Entrada",
  [FeatureType.Selectivo]: "Selectivo",
  [FeatureType.Concurso]: "Concurso",
  [FeatureType.Global]: "Global",
  [FeatureType.Local]: "Local",
  [FeatureType.Asimov]: "Asimov",
  [FeatureType.ConcursoInterno1]: "Concurso interno 1",
  [FeatureType.ConcursoExterno]: "Concurso externo",
  [FeatureType.ConcursoInterno2]: "Concurso interno 2",
  [FeatureType.Merito]: "Mérito",
  [FeatureType.ConcursoInterno3]: "Concurso interno 3",
  [FeatureType.DecisionInterna]: "Decisión interna",
  [FeatureType.TForm]: "T-Form",
  [FeatureType.CrecimientoDelNegocio]: "Crecimiento del negocio",
  [FeatureType.TransformacionDesdeReSources]: "Transformación desde ReSources",
  [FeatureType.Reestructuracion]: "Reestructuración",
  [FeatureType.Maternidad]: "Maternidad",
  [FeatureType.Enfermedad]: "Enfermedad",
  [FeatureType.NecesidadDeNegocio]: "Necesidad de negocio",
};
